wip: started typescript migration
humanprotocol/escrow-dashboard pull request #28
Opened 2022-06-02 13:05 UTC by makarofalex3

started typescript migration

2022-06-07 13:51 UTC, vkomodey requested changes
Do we need to update run instructions here(both local and remote in the docker)?

Also, I see a bunch of files with js and jsx extensions. Do we really need to preserve these extensions?

2022-06-07 13:55 UTC, makarofalex3 commented on src/theme.tsx
> +      // white: '#f5f5f5'
yes we can!

2022-06-08 07:17 UTC, makarofalex3 commented on src/utils/index.ts
> +export const countEscrowFactory = (escrowFactories: Array<any>) => {
added

2022-06-08 07:17 UTC, makarofalex3 commented on src/theme.tsx
> +      // white: '#f5f5f5'
fixed

2022-06-08 09:51 UTC, vkomodey commented
What about running instructions(both local and remote)? Are they the same as were before?

2022-06-08 10:53 UTC, merged