escrow factory dashboard update
humanprotocol/escrow-dashboard pull request #3
Opened 2022-04-12 16:45 UTC by cartoonweber

2022-04-12 17:34 UTC, Human-Protocol commented
@cartoonweber This is not ready to go

1) Squash these commits
2) Put a decent commit message on the PR
3) Get rid of all the commented out code
4) Please cleanup the code for nits

2022-04-12 17:36 UTC, Human-Protocol requested changes
@cartoonweber This is not ready to go

Squash these commits
Put a decent commit message on the PR
Get rid of all the commented out code
Please cleanup the code for nits

2022-04-12 17:36 UTC, Human-Protocol commented on src/components/Main.js
> +  // const onNetworkChange = (networkKey) => {
what's this about?

2022-04-13 11:45 UTC, vkomodey requested changes
1. Please, write decent commit messages and organize 2-3 commits. not 45
2. Remove all console.log statements. They are useless in production
3. A lot of commented code. Don't use it at all please
4. A lot of custom styles used. Try to use generic components with their own styles and use them instead + don't forget about MUI theme(no need to redefine your colors in the main css file
5. We have 1 factory per network right now and they are pretty hardcoded. The table with pagination is a bad element for just 2 rows .It is good for escrows inside, because we have a lot of them. Let's use a different element for escrow. You might suggest it within the slack channel or here in PR. Use UX best practices for that
6. Since you display 2 factories in the table I don't get how the search bar works now(particulary if you don't have a current network where to find the escrow). We either don't need it or specify a clear behavior with the table below(but I'm pretty sure, we need some modifications to the whole design to make it happened)
7. The factory table displays the balance of the latest escrow. It is a redundant information about the factory. Possible useful values are - total amount of HMT for this factory, total amount of Escrows and etc.
8. Seems that network switcher is redundant now
9. Please, try to avoid using `!important` statements in your CSS. This make the code harder to extend

2022-04-13 11:45 UTC, vkomodey commented on src/components/Footer.js
> +                <MailchimpFormContainer />
We are not using mailchimp for that. Let's do it in different PR and remove the logic here

2022-04-13 11:45 UTC, vkomodey commented on src/components/Footer.js
> +                    </a>
Links should lead to the right resource. Now they are empty and useless

2022-04-13 11:45 UTC, vkomodey commented on src/components/Footer.js
> +                    </a>
visit the https://humanprotocol.org and copy all resources(links)

2022-04-13 11:45 UTC, vkomodey commented on src/components/Footer.js
> +            © 2021 HPF. HUMAN Protocol® is a registered trademark
2022

2022-04-13 11:45 UTC, vkomodey commented on src/components/Footer.js
> +                <a>contact@hmt.ai</a>
this should have a mailto parameter

2022-04-13 11:45 UTC, vkomodey commented on package.json
> +    "ethers": "^5.6.2",
already using web3. why do you need an additional library?

2022-04-13 11:45 UTC, vkomodey commented on src/components/Escrow.js
> +                setScanner('https://polygonscan.com');
you should get this value from the configuration(or constants) instead of hardcoding it

2022-04-13 11:45 UTC, vkomodey commented on src/components/Escrow.js
> +                EscrowFactory.on('Launched', async (eip, escrow) => {
Launching a new job is not something we would like to subscribe into. This is a pretty rare event. Don't think we need this logic

2022-04-13 11:45 UTC, vkomodey commented on src/components/Escrow.js
> +                console.log("error_", err);
DRY: you have 2 identical pieces of code(for different networks)
What we'd like to have - is to easy to manipulate configuration, where everyone can add a specific configuration(including addresses, scan url, rpc api url, chain id and etc.) and see changes in the UI

2022-04-13 11:45 UTC, vkomodey commented on src/components/EscrowFactoryView.js
> +    {id: 'network', label: 'NetWork', minWidth: 150},
Net**w**ork

2022-04-13 16:55 UTC, closed without merging