wip: Feat/add jobs from thegraph
humanprotocol/escrow-dashboard pull request #40
Opened 2022-06-08 11:11 UTC by makarofalex3

wip: Feat/add jobs from thegraph

2022-06-14 12:26 UTC, vkomodey commented
@makarofalex3 CI doesn't work. Need a fix

2022-06-14 12:27 UTC, vkomodey commented
Please, add PR description with detailed explanation what(and why) this was implemented as well

2022-06-14 14:16 UTC, vkomodey requested changes
You updated yarn. Need to update instructions in the README file

2022-06-14 15:35 UTC, makarofalex3 commented on src/queries/index.ts
> +export const IS_EVENT = gql`
fixed

2022-06-14 15:35 UTC, makarofalex3 commented on package.json
> +    "@types/react-window": "^1.8.5",
fixed

2022-06-14 15:35 UTC, makarofalex3 commented on Dockerfile
> +COPY tsconfig.json ./
fixed

2022-06-15 12:53 UTC, vkomodey requested changes
The layout is broken for the last block. Compare current dashboard and yours
![image](https://user-images.githubusercontent.com/7757858/173831508-34d4afae-31b8-457f-981f-52cd1fe9b1fb.png)
![image](https://user-images.githubusercontent.com/7757858/173831545-ff192c04-724d-4e43-82db-078e1471c2d2.png)

2022-06-17 10:32 UTC, merged